"""Canvas Documents Service.

Interactive, sandboxed canvas documents and widgets generated by the agent
or user (inspired by Antigravity Core src/canvas and extensions/canvas).
Handles document materialization, HTML wrapping with theme bridge, CSP headers,
and directory sandboxing.
"""

from __future__ import annotations

import html
import json
import logging
import os
import re
import shutil
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from app.config import GEMINI_DIR
from app.platform_utils import is_blocked_sensitive_path

logger = logging.getLogger("antigravity.canvas_documents")


CanvasDocumentKind = Literal["html_bundle", "url_embed", "document", "image", "video_asset"]
CanvasSurface = Literal["assistant_message", "tool_card", "sidebar"]

CANVAS_DOCUMENTS_PATH_PREFIX = "/api/canvas/documents"
MAX_CANVAS_DOCUMENT_BYTES = 10 * 1024 * 1024  # 10 MB limit


class CanvasDocumentAsset(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    logical_path: str = Field(..., alias="logicalPath")
    source_path: str = Field(..., alias="sourcePath")
    content_type: str | None = Field(None, alias="contentType")


class CanvasDocumentEntrypoint(BaseModel):
    type: Literal["html", "path", "url"]
    value: str


class CanvasDocumentCreateInput(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    id: str | None = None
    kind: CanvasDocumentKind = "html_bundle"
    title: str | None = None
    preferred_height: int | None = Field(None, alias="preferredHeight")
    entrypoint: CanvasDocumentEntrypoint
    assets: list[CanvasDocumentAsset] | None = None
    surface: CanvasSurface | None = "assistant_message"
    retention_scope: str | None = Field(None, alias="retentionScope")
    csp_sandbox: Literal["scripts"] | None = Field("scripts", alias="cspSandbox")
    wrap_with_theme: bool = Field(True, alias="wrapWithTheme")


class CanvasDocumentManifest(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    id: str
    kind: CanvasDocumentKind
    title: str | None = None
    preferred_height: int | None = Field(None, alias="preferredHeight")
    created_at: str = Field(..., alias="createdAt")
    entry_url: str = Field(..., alias="entryUrl")
    local_entrypoint: str | None = Field(None, alias="localEntrypoint")
    external_url: str | None = Field(None, alias="externalUrl")
    surface: CanvasSurface | None = "assistant_message"
    retention_scope: str | None = Field(None, alias="retentionScope")
    csp_sandbox: Literal["scripts"] | None = Field("scripts", alias="cspSandbox")
    assets: list[dict[str, str]] = Field(default_factory=list)


# Theme variables and responsive CSS injected into HTML widgets
WIDGET_BASE_STYLES = """
:root {
  color-scheme: light dark;
  --surface: #faf9f7;
  --card: #ffffff;
  --elevated: #ffffff;
  --text: #403c35;
  --text-strong: #211e1a;
  --muted: #6e6960;
  --border: #e8e4dc;
  --border-strong: #d6d0c5;
  --accent: #6366f1;
  --accent-fill: #4f46e5;
  --accent-fg: #ffffff;
  --ok: #15803d;
  --warn: #b45309;
  --danger: #dc2626;
  --info: #2563eb;
  --radius: 10px;
  --radius-full: 9999px;
  --font-body: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  --font-mono: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;
}
@media (prefers-color-scheme: dark) {
  :root {
    --surface: #0e1015;
    --card: #161920;
    --elevated: #191c24;
    --text: #d4d4d8;
    --text-strong: #f4f4f5;
    --muted: #8b8b94;
    --border: #1e2028;
    --border-strong: #2e3040;
    --accent: #818cf8;
    --accent-fill: #6366f1;
    --accent-fg: #ffffff;
    --ok: #22c55e;
    --warn: #f59e0b;
    --danger: #ef4444;
    --info: #3b82f6;
  }
}
* { box-sizing: border-box; }
html, body {
  margin: 0;
  padding: 0;
  font-family: var(--font-body);
  color: var(--text);
  background: var(--surface);
  line-height: 1.5;
  font-size: 14px;
}
"""

WIDGET_BRIDGE_SCRIPT = """
<script>
(function() {
  // Theme sync from parent
  window.addEventListener('message', function(event) {
    if (!event || !event.data) return;
    if (event.data.type === 'canvas:theme' && event.data.tokens) {
      var root = document.documentElement;
      for (var key in event.data.tokens) {
        if (Object.prototype.hasOwnProperty.call(event.data.tokens, key)) {
          root.style.setProperty(key, event.data.tokens[key]);
        }
      }
      if (event.data.theme) {
        root.setAttribute('data-theme', event.data.theme);
      }
    }
  });

  // Auto-resize reporter
  function reportSize() {
    var height = Math.max(
      document.body ? document.body.scrollHeight : 0,
      document.documentElement ? document.documentElement.scrollHeight : 0
    );
    if (window.parent && window.parent !== window) {
      window.parent.postMessage({ type: 'canvas:resize', height: height }, '*');
    }
  }

  window.addEventListener('load', reportSize);
  window.addEventListener('resize', reportSize);
  if (typeof ResizeObserver !== 'undefined' && document.body) {
    try {
      new ResizeObserver(reportSize).observe(document.body);
    } catch(e) {}
  }
})();
</script>
"""


def resolve_canvas_documents_dir() -> Path:
    """Return the base storage directory for Canvas documents."""
    docs_dir = GEMINI_DIR / "canvas" / "documents"
    docs_dir.mkdir(parents=True, exist_ok=True)
    return docs_dir


def normalize_canvas_document_id(value: str) -> str:
    """Validate and sanitize canvas document id."""
    normalized = value.strip()
    if not normalized or normalized in (".", "..") or not re.match(r"^[A-Za-z0-9._-]+$", normalized):
        raise ValueError(f"Invalid canvas document id: {value}")
    return normalized


def generate_canvas_document_id() -> str:
    """Generate a stable prefixed document ID."""
    return f"cv_{uuid.uuid4().hex[:12]}"


def normalize_logical_path(value: str) -> str:
    """Normalize and security-check logical asset path."""
    normalized = value.replace("\\", "/").lstrip("/")
    parts = [p for p in normalized.split("/") if p]
    if not parts or any(p in (".", "..") or ":" in p or any(ord(c) < 32 or ord(c) == 127 for c in p) for p in parts):
        raise ValueError(f"Invalid canvas logicalPath: {value}")
    return "/".join(parts)


def sanitize_filename(filename: str, default_name: str = "asset") -> str:
    """Sanitize filename to prevent directory traversal or reserved character issues."""
    name = re.sub(r'[^\w\-.]', '_', filename).strip("._")
    return name if name else default_name


def wrap_canvas_html(raw_html: str, title: str | None = None) -> str:
    """
    Wraps raw HTML content with Antigravity design tokens, base styles,
    and the postMessage theme & resize bridge.
    """
    page_title = html.escape(title or "Canvas Widget")
    lower = raw_html.lower()

    # If it is already a full HTML document, inject styles and script into <head> or <body>
    if "<html" in lower and "<head" in lower:
        style_tag = f"<style>{WIDGET_BASE_STYLES}</style>"
        injected = re.sub(
            r"(<head[^>]*>)",
            rf"\1\n{style_tag}\n{WIDGET_BRIDGE_SCRIPT}",
            raw_html,
            count=1,
            flags=re.IGNORECASE,
        )
        return injected

    # Otherwise wrap snippet in a complete HTML document
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{page_title}</title>
  <style>{WIDGET_BASE_STYLES}</style>
  {WIDGET_BRIDGE_SCRIPT}
</head>
<body>
{raw_html}
</body>
</html>"""


def build_pdf_wrapper(url: str) -> str:
    """Build an HTML preview wrapper for a PDF asset or external URL."""
    escaped = html.escape(url)
    return f"""<!doctype html>
<html>
<body style="margin:0;background:#1e2028;">
  <object data="{escaped}" type="application/pdf" style="width:100%;height:100vh;border:0;">
    <iframe src="{escaped}" style="width:100%;height:100vh;border:0;"></iframe>
    <p style="padding:16px;color:#d4d4d8;font:14px system-ui,sans-serif;">
      Unable to render PDF preview. <a href="{escaped}" target="_blank" rel="noopener noreferrer" style="color:#818cf8;">Open PDF directly</a>.
    </p>
  </object>
</body>
</html>"""


def build_canvas_document_entry_url(doc_id: str, entrypoint: str) -> str:
    """Build the hosted HTTP URL path for an entrypoint."""
    normalized = normalize_logical_path(entrypoint)
    return f"{CANVAS_DOCUMENTS_PATH_PREFIX}/{doc_id}/serve/{normalized}"


def create_canvas_document(
    input_data: CanvasDocumentCreateInput,
    workspace_dir: str | None = None,
    max_documents_per_scope: int = 50,
) -> CanvasDocumentManifest:
    """Creates a Canvas document folder, writes files/manifest, and applies scoping."""
    doc_id = normalize_canvas_document_id(input_data.id) if input_data.id else generate_canvas_document_id()
    docs_base_dir = resolve_canvas_documents_dir()
    doc_dir = docs_base_dir / doc_id

    # Security check: ensure target directory is strictly within docs_base_dir
    if not doc_dir.resolve().is_relative_to(docs_base_dir.resolve()):
        raise ValueError(f"Path traversal detected in doc_id: {doc_id}")

    if doc_dir.exists():
        shutil.rmtree(doc_dir, ignore_errors=True)
    doc_dir.mkdir(parents=True, exist_ok=True)

    copied_assets: list[dict[str, str]] = []
    ws_dir = Path(workspace_dir).resolve() if workspace_dir else Path.cwd().resolve()

    # Process and copy assets if provided
    if input_data.assets:
        for asset in input_data.assets:
            logical_path = normalize_logical_path(asset.logical_path)
            target_asset_file = doc_dir / logical_path
            target_asset_file.parent.mkdir(parents=True, exist_ok=True)

            source_path = Path(os.path.expanduser(asset.source_path))
            if not source_path.is_absolute():
                source_path = (ws_dir / source_path).resolve()
            else:
                source_path = source_path.resolve()

            if is_blocked_sensitive_path(source_path):
                raise PermissionError(f"Access denied to sensitive file: {source_path}")

            if source_path.exists() and source_path.is_file():
                shutil.copy2(source_path, target_asset_file)
                asset_meta = {"logicalPath": logical_path}
                if asset.content_type:
                    asset_meta["contentType"] = asset.content_type
                copied_assets.append(asset_meta)
            else:
                logger.warning(f"Canvas asset source not found: {source_path}")

    # Materialize entrypoint
    entry = input_data.entrypoint
    local_entrypoint: str | None = None
    external_url: str | None = None
    entry_url: str = ""

    if entry.type == "html":
        filename = "index.html"
        final_html = wrap_canvas_html(entry.value, input_data.title) if input_data.wrap_with_theme else entry.value
        (doc_dir / filename).write_text(final_html, encoding="utf-8")
        local_entrypoint = filename
        entry_url = build_canvas_document_entry_url(doc_id, filename)

    elif entry.type == "url":
        url_val = entry.value.strip()
        if input_data.kind == "document" and url_val.lower().endswith(".pdf"):
            filename = "index.html"
            (doc_dir / filename).write_text(build_pdf_wrapper(url_val), encoding="utf-8")
            local_entrypoint = filename
            external_url = url_val
            entry_url = build_canvas_document_entry_url(doc_id, filename)
        else:
            external_url = url_val
            entry_url = url_val

    elif entry.type == "path":
        source_path = Path(os.path.expanduser(entry.value))
        if not source_path.is_absolute():
            source_path = (ws_dir / source_path).resolve()
        else:
            source_path = source_path.resolve()

        if is_blocked_sensitive_path(source_path):
            raise PermissionError(f"Access denied to sensitive file: {source_path}")

        if not source_path.exists():
            raise FileNotFoundError(f"Entrypoint file not found: {source_path}")

        if input_data.kind in ("image", "video_asset"):
            asset_name = sanitize_filename(source_path.name, "media")
            shutil.copy2(source_path, doc_dir / asset_name)
            media_tag = (
                f'<img src="{html.escape(asset_name)}" style="max-width:100%;max-height:100vh;object-fit:contain;" />'
                if input_data.kind == "image"
                else f'<video src="{html.escape(asset_name)}" controls autoplay style="width:100%;height:100vh;object-fit:contain;background:#000;"></video>'
            )
            index_content = f"""<!doctype html><html><body style="margin:0;background:#0e1015;display:flex;align-items:center;justify-content:center;">{media_tag}</body></html>"""
            (doc_dir / "index.html").write_text(index_content, encoding="utf-8")
            local_entrypoint = "index.html"
            entry_url = build_canvas_document_entry_url(doc_id, "index.html")
        elif input_data.kind == "document" and source_path.name.lower().endswith(".pdf"):
            doc_name = sanitize_filename(source_path.name, "doc.pdf")
            shutil.copy2(source_path, doc_dir / doc_name)
            (doc_dir / "index.html").write_text(build_pdf_wrapper(doc_name), encoding="utf-8")
            local_entrypoint = "index.html"
            entry_url = build_canvas_document_entry_url(doc_id, "index.html")
        else:
            doc_name = sanitize_filename(source_path.name, "index.html")
            if doc_name.lower().endswith(".html") and input_data.wrap_with_theme:
                content = source_path.read_text(encoding="utf-8")
                (doc_dir / doc_name).write_text(wrap_canvas_html(content, input_data.title), encoding="utf-8")
            else:
                shutil.copy2(source_path, doc_dir / doc_name)
            local_entrypoint = doc_name
            entry_url = build_canvas_document_entry_url(doc_id, doc_name)

    manifest = CanvasDocumentManifest(
        id=doc_id,
        kind=input_data.kind,
        title=input_data.title,
        preferred_height=input_data.preferred_height,
        created_at=datetime.now(timezone.utc).isoformat(),
        entry_url=entry_url,
        local_entrypoint=local_entrypoint,
        external_url=external_url,
        surface=input_data.surface,
        retention_scope=input_data.retention_scope,
        csp_sandbox=input_data.csp_sandbox,
        assets=copied_assets,
    )

    manifest_file = doc_dir / "manifest.json"
    manifest_file.write_text(manifest.model_dump_json(by_alias=True, indent=2), encoding="utf-8")

    # Prune old documents if scoped
    if input_data.retention_scope and max_documents_per_scope > 0:
        prune_canvas_documents_for_scope(input_data.retention_scope, max_documents_per_scope)

    return manifest


def get_canvas_document(doc_id: str) -> CanvasDocumentManifest | None:
    """Load a canvas document manifest by id."""
    try:
        norm_id = normalize_canvas_document_id(doc_id)
        docs_base_dir = resolve_canvas_documents_dir()
        manifest_path = docs_base_dir / norm_id / "manifest.json"
        if not manifest_path.exists():
            return None
        data = json.loads(manifest_path.read_text(encoding="utf-8"))
        return CanvasDocumentManifest(**data)
    except Exception as e:
        logger.debug(f"Error loading canvas document {doc_id}: {e}")
        return None


def list_canvas_documents(
    retention_scope: str | None = None,
    kind: str | None = None,
    limit: int = 50,
) -> list[CanvasDocumentManifest]:
    """List stored canvas documents, newest first."""
    docs_base_dir = resolve_canvas_documents_dir()
    manifests: list[CanvasDocumentManifest] = []

    if not docs_base_dir.exists():
        return []

    for entry in docs_base_dir.iterdir():
        if entry.is_dir():
            manifest_file = entry / "manifest.json"
            if manifest_file.exists():
                try:
                    data = json.loads(manifest_file.read_text(encoding="utf-8"))
                    doc = CanvasDocumentManifest(**data)
                    if retention_scope and doc.retention_scope != retention_scope:
                        continue
                    if kind and doc.kind != kind:
                        continue
                    manifests.append(doc)
                except Exception:
                    continue

    manifests.sort(key=lambda d: d.created_at, reverse=True)
    return manifests[:limit]


def delete_canvas_document(doc_id: str) -> bool:
    """Delete a canvas document and its files."""
    try:
        norm_id = normalize_canvas_document_id(doc_id)
        docs_base_dir = resolve_canvas_documents_dir()
        doc_dir = docs_base_dir / norm_id
        if doc_dir.exists() and doc_dir.resolve().is_relative_to(docs_base_dir.resolve()):
            shutil.rmtree(doc_dir, ignore_errors=True)
            return True
        return False
    except Exception as e:
        logger.warning(f"Error deleting canvas document {doc_id}: {e}")
        return False


def resolve_canvas_file_path(doc_id: str, relative_path: str = "") -> Path | None:
    """
    Safely resolves a file path within a canvas document directory.
    Guarantees no directory traversal outside the document's folder.
    """
    norm_id = normalize_canvas_document_id(doc_id)
    docs_base_dir = resolve_canvas_documents_dir()
    doc_dir = (docs_base_dir / norm_id).resolve()

    if not doc_dir.exists() or not doc_dir.is_relative_to(docs_base_dir.resolve()):
        return None

    if not relative_path or relative_path == "/":
        # Resolve entrypoint from manifest
        manifest = get_canvas_document(norm_id)
        if manifest and manifest.local_entrypoint:
            relative_path = manifest.local_entrypoint
        else:
            relative_path = "index.html"

    clean_rel = normalize_logical_path(relative_path)
    target = (doc_dir / clean_rel).resolve()

    if not target.exists() or not target.is_relative_to(doc_dir):
        return None

    return target


def prune_canvas_documents_for_scope(scope: str, max_docs: int) -> int:
    """Prunes oldest documents in a given retention scope down to max_docs."""
    manifests = list_canvas_documents(retention_scope=scope, limit=1000)
    if len(manifests) <= max_docs:
        return 0

    to_delete = manifests[max_docs:]
    deleted = 0
    for doc in to_delete:
        if delete_canvas_document(doc.id):
            deleted += 1
    return deleted
